name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

  - name: Setup SSH
      uses: webfactory/ssh-agent@v20
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Namecheap
      run: |
        ssh -o StrictHostKeyChecking=no zedaeeqz@162.0.209.71 'cd /home/zedaeeqz/zedapp && git pull'