name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Deploy to Namecheap
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NAMECHEAP_USERNAME }}
        password: ${{ secrets.NAMECHEAP_PASSWORD }}
        debug: true
        script: |
          cd /home/zedaeeqz/zedapp
          git pull